apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iv98a35gy-nodejs
  janus-idp.io/tekton: iv98a35gy-nodejs
  backstage.io/kubernetes-id: iv98a35gy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iv98a35gy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
